### ISSUE TITLE
Event Repeater Dangling  Pointer

### ISSUE THREAD

**Issue by jwdfki** [BertoldVdb/FreeRTOS-ChibiOSAL#1]
After the line:
https://github.com/BertoldVdb/FreeRTOS-ChibiOSAL/blob/ce19735a78522bacc5a76ec99e1fc0855dcb0b50/FreeRTOS/osal_ch.c#L191
The new first element of the list should be marked as such by doing
```
event_repeater->source->firstRepeater->prevRepeater = NULL; // mark as new first
```

otherwise the new first element will not pass the test of
https://github.com/BertoldVdb/FreeRTOS-ChibiOSAL/blob/ce19735a78522bacc5a76ec99e1fc0855dcb0b50/FreeRTOS/osal_ch.c#L190
and the list gets corrupted

**Comment by BertoldVdb** [comment]
You are right! Thank you. I will fix it.
